### ISSUE TITLE
 Trouble with ultrawide monitor

### ISSUE THREAD

**Issue by s1snake** [lazydevyo/PSVitaDock#2]
Hi. I have 2 monitors: 21:9 and 16:9. 21:9 - main.
The application starts with a ratio of main monitor - 21:9. How i can fix it?
p.s and this colorful lines.. it's normal? or this can be fixed?

thx for the answer

**Comment by lazydevyo** [comment]
Ill fix it in the new version, the lines are watermark from the plugin thats been used which is free.

**Comment by MyFilippo94** [comment]
I have the same issue, although  a new version was released, this problem is still there. I have a 21:9 screen and a 16:10 one. Please add an option to choose between stretch and keep ratio, it's really needed to enjoy this application in fullscreen
