### ISSUE TITLE
Audio from vita buzzes only when using PSVitaDock.

### ISSUE THREAD

**Issue by fakusnamus** [lazydevyo/PSVitaDock#8]
The audio plays fine when PSVitaDock is not open when doing "listen to this device" on the line in/microphone (I've tried assigning the vita to both), and I've put PSVita suffix in each one. But the moment I open PSVitaDock, the audio immediately starts buzzing hard. I've tried doing this with the power supply of the laptop both connected and disconnected. This doesn't affect the buzzing. Once vita dock starts, even the "listen to this device" audio starts buzzing _if_ that's left on.

**Comment by ExtremeCaliber** [comment]
Supposedly, if you go into your vita settings and turn off charge via usb, it's supposed to fix the interference. I didn't have to do it myself since my aux cable is sort of well made

**Comment by lazydevyo** [comment]
Thats because electrostatic enegry from the usb port reaches the audio port, simple don't charge your vita while using it like said by ExtremeCaliber's ^ on top anwser.
